name: app
version: 0.1.0.0
synopsis: "Slime Drawing app"
category: Desktop

dependencies:
  - base
  - containers
  - random
  - mtl
  - vector
  - microlens-platform
  - microlens-mtl
  - MonadRandom
  - gloss
  - massiv

executables:
  app:
    main: Main.hs
    source-dirs: app
    language: GHC2024
    ghc-options: -threaded

